; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
	
	; ottowinter/ESPAsyncWebServer-esphome@^1.2.7
	; knolleary/PubSubClient@^2.8
	; adafruit/Adafruit DAP library@^1.8.0
	; bblanchon/ArduinoJson@^6.18.0
	; adafruit/Adafruit NeoPixel@^1.10.0

[env:featheresp32]
platform = espressif32
board = featheresp32
upload_port = COM6
monitor_port = COM6
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
	-DARDUINO_LOOP_STACK_SIZE=24576
	-DNIVALO_HAS_SECONDARY_MCU=1
extra_scripts =
	pre:scripts/patch_adafruit_dap_stm32.py
board_upload.flash_size = 4MB
board_upload.maximum_size = 1310720
lib_deps = 
	symlink://../..
	adafruit/Adafruit DAP library@^1.8.0
	ottowinter/ESPAsyncWebServer-esphome@^1.2.7
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.18.0
	adafruit/Adafruit NeoPixel@^1.10.0
