[env:featheresp32]
platform = espressif32@7.0.1
board = featheresp32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DARDUINO_LOOP_STACK_SIZE=24576
lib_deps =
    symlink://../..
    knolleary/PubSubClient@2.8
    bblanchon/ArduinoJson@6.21.6
    adafruit/Adafruit NeoPixel@1.15.5
